apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 labels:
  app: mysql
spec:
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
   - name: mysql
     image: mysql-image
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
 name: mysql
 labels:
  app: mysql
spec:
 ports:
 - name: sql
   port: 3306
   targetPort: 3306
   protocol: TCP
 clusterIP: None
 selector:
  app: nginx