apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 labels:
  app: nginx
spec:
 type: NodePort
 ports:
 - name: ssh
   port: 22
   nodePort: 30001
   targetPort: 22
   protocol: TCP
 - name: https
   port: 443
   nodePort: 30002
   targetPort: 443
   protocol: TCP
 - name: http
   port: 80
   nodePort: 30003
   targetPort: 80
   protocol: TCP
 selector:
  app: nginx