apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
 labels:
  app: wordpress
spec:
 selector:
  matchLabels:
   app: wordpress
 template:
  metadata:
   labels:
    app: wordpress
  spec:
   containers:
   - name: wordpress
     image: wordpress-image
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
 name: wordpress
 annotations:
  metallb.universe.tf/allow-shared-ip: sharing key
 labels:
  app: phpmyadmin
spec:
 type: LoadBalancer
 ports:
 - name: wordpress
   port: 5050
   targetPort: 5050
   protocol: TCP
 clusterIP: 10.106.164.250
 selector:
  app: wordpress